version: "2.1"

services:
  oracle-xe:
    image: daggerok/oracle:12.1.0.2
    shm_size: 1g
    environment:
      ORACLE_PWD: satdev
    ports:
    - "1521:1521"
    - "8080:8080"
    volumes:
    - "oracle-xe-data:/u01/app/oracle/oradata"
    - "./db-startup-migration-scripts:/u01/app/oracle/scripts/startup"
    - "./db-setup-migration-scripts:/docker-entrypoint-initdb.d/setup"
    networks: [backing-services]
    restart: unless-stopped

volumes:
  oracle-xe-data: {}

networks:
  backing-services:
    driver: bridge