version: '3.4'

networks: 
  monitoring:
    driver: bridge 
    
services:

 
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    volumes:
      - ./env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - monitoring
   
 
  grafana:
    image: grafana/grafana:7.3.3
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./env/grafana.env
    networks:
      - monitoring
   
      
      