FROM jboss/keycloak:12.0.4

# COPY ./standalone-ha.xml /opt/jboss/keycloak/standalone/configuration/standalone-ha.xml

RUN sed -i -E "s/(<staticMaxAge>)2592000(<\/staticMaxAge>)/\1\-1\2/" /opt/jboss/keycloak/standalone/configuration/standalone.xml
RUN sed -i -E "s/(<cacheThemes>)true(<\/cacheThemes>)/\1false\2/" /opt/jboss/keycloak/standalone/configuration/standalone.xml
RUN sed -i -E "s/(<cacheTemplates>)true(<\/cacheTemplates>)/\1false\2/" /opt/jboss/keycloak/standalone/configuration/standalone.xml

COPY ./json /tmp
COPY ./themes/ecotx /opt/jboss/keycloak/themes/ecotx
COPY ./plugins /opt/jboss/keycloak/standalone/deployments